apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: openshift-cnv
  project: default
  source:
    path: applications/kubevirt
    repoURL: git@github.com:rh-dttl-edge-virt-demo/hub-bootstrap.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
        openshift.io/cluster-monitoring: "true"
