---
global:
  postCode: "EXAMPLE"
  applicationVersion: v0.1.0

windows10Image:
  extraCommands:
    - commandLine: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -Command "& {$AppLoc = 'C:\Program Files\ExamplePostApp\ExamplePostApp.exe'; New-Item -ItemType Directory -Force -Path 'C:\Program Files\ExamplePostApp'; Do { Invoke-RestMethod -OutFile $AppLoc -Uri 'https://s3.jharmison.com/public/ExamplePostApp-{{ .Values.global.applicationVersion }}.exe' -TimeoutSec 10 -UseBasicParsing } While ( -not (Test-Path $AppLoc) ); Unblock-File -Path $AppLoc; $WshShell = New-Object -comObject WScript.Shell; $Shortcut = $WshShell.CreateShortcut('C:\Users\Administrator\Desktop\ExamplePostApp.lnk'); $Shortcut.TargetPath = $AppLoc; $Shortcut.save(); [System.Environment]::SetEnvironmentVariable('POST_CD', '{{ .Values.global.postCode }}', 'Machine'); Start-Sleep -Seconds 5; Stop-Computer -ComputerName localhost -Force; }"
      description: Downloads the Post application
