---
global:
  postCode: "EXAMPLE"
  applicationVersion: v0.1.0

windows10Image:
  postInstallPowershell: |-
    # Wait for networking before performing the download
    do {
      $ping = Test-Connection -Comp kubevirt.io -Count 1 -Quiet
    } until (
      $ping
    )

    # Download the legacy app
    $AppLoc = 'C:\Program Files\ExamplePostApp\ExamplePostApp.exe'
    New-Item -ItemType Directory -Force -Path 'C:\Program Files\ExamplePostApp'
    Do {
      Invoke-RestMethod -OutFile $AppLoc -Uri 'https://s3.jharmison.com/public/ExamplePostApp-{{ .Values.global.applicationVersion }}.exe' -TimeoutSec 10 -UseBasicParsing
    } While (
      -not (Test-Path $AppLoc)
    )
    Unblock-File -Path $AppLoc

    # Configure the shortcut
    $WshShell = New-Object -comObject WScript.Shell
    $Shortcut = $WshShell.CreateShortcut('C:\Users\Administrator\Desktop\ExamplePostApp.lnk')
    $Shortcut.TargetPath = $AppLoc
    $Shortcut.save()

    # Set the post code
    [System.Environment]::SetEnvironmentVariable('POST_CD', '{{ .Values.global.postCode }}', 'Machine')
