apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modern-post-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: dos
  project: default
  source:
    path: applications/modern-post-app
    repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - /clusters/{{ $.Values.cluster.name }}/modern-post-app/values.yaml
        - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/{{ $.Values.cluster.name }}/modern-post-app/secrets.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
        openshift.io/cluster-monitoring: "true"
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
