apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: applications/config
    repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - /clusters/{{ $.Values.cluster.name }}/config/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
