---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
    namespace: open-cluster-management
  project: default
  source:
    path: applications/cert-manager
    repoURL: git@github.com:rh-dttl-edge-virt-demo/hub-bootstrap.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
