---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraenv
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: open-cluster-management
  project: default
  source:
    path: applications/infraenv
    repoURL: git@github.com:rh-dttl-edge-virt-demo/hub-bootstrap.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/argo.txt?secrets.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
