---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-certificates
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - git:
        repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
        revision: HEAD
        files:
          - path: "clusters/**/provision.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{ cluster.name }}-certificates"
    spec:
      destination:
        name: in-cluster
        namespace: "{{ cluster.env }}"
      project: default
      source:
        path: applications/cluster-certificates
        repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - "/clusters/{{ cluster.name }}/provision.yaml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
