---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - git:
        repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
        revision: HEAD
        files:
          - path: "clusters/**/provision.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{ cluster.name }}-applications"
    spec:
      destination:
        name: in-cluster
        namespace: "{{ cluster.name }}"
      project: default
      source:
        path: applications/cluster-applications
        repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - "/clusters/{{ cluster.name }}/provision.yaml"
            - secrets+age-import:///helm-secrets-private-keys/argo.txt?../../clusters/{{ cluster.name }}/secrets.enc.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
