---
replicaCount: 1

postCode: TRT.PROD

image:
  registry: docker.io
  repository: lindseyvolk/examplepostapp-modernized
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  annotations: {}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
