---
storageDeviceSets:
  - config: {}
    count: 3
    monDataDirHostPath: /var/lib/rook
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: localblock
        volumeMode: Block
      status: {}
    name: ocs-deviceset-localblock
    placement: {}
    portable: false
    preparePlacement: {}
    replica: 1
    resources: {}
