---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
