---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{ .Values.cluster.name }}
spec:
  platformType: {{ .Values.cluster.platformType }}
  {{- with .Values.cluster.platform }}
  platform:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  imageSetRef:
    name: img{{ .Values.cluster.version }}-{{ .Values.cluster.arch }}-appsub
  networking:
    {{- toYaml .Values.cluster.networking | nindent 4 }}
  provisionRequirements:
    controlPlaneAgents: {{ .Values.cluster.controlPlaneNodes }}
    {{- with .Values.cluster.workerNodes }}
    workerAgents: {{ . }}
    {{- end }}
  sshPublicKey: {{ .Values.sshKey }}
  mastersSchedulable: {{ if lt (int .Values.cluster.workerNodes) 2 }}true{{ else }}false{{ end }}
  {{- with .Values.cluster.apiVIPs }}
  apiVIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cluster.ingressVIPs }}
  ingressVIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
