---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: update-manifests
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-manifests-api-cert
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certificates.cert-manager.io-v1-view
subjects:
- kind: ServiceAccount
  name: update-manifests
  namespace: {{ .Release.Namespace }}
{{- if .Values.nodes }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-agents-{{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.env }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-agents
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: update-agents-{{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.env }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-agents-{{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.env }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: update-agents-{{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.env }}
{{- end }}
