apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: openshift-local-storage
  project: default
  source:
    path: applications/local-storage-operator
    repoURL: git@github.com:rh-dttl-edge-virt-demo/edge-virt.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - /clusters/{{ $.Values.cluster.name }}/local-storage-operator/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
        openshift.io/cluster-monitoring: "true"
