---
acme:
  zerossl:
    server: https://acme.zerossl.com/v2/DV90
    email: jharmison@redhat.com
    externalAccountBinding:
      keyID: hc07gV_4sxOseabTphAMsg
      keySecretRef:
        name: acme-zerossl-eabsecret
        key: secret
      keyAlgorithm: HS256
    solvers:
      - type: dns
        dnsConfig:
          route53:
            accessKeyID: AKIAYXH2S2VGCXPPTBC7
            hostedZoneID: Z08911972ABVHLQPO8VYV
            region: us-east-2
            secretAccessKeySecretRef:
              key: secret-access-key
              name: acme-zerossl-route53-creds
        dnsZones:
          - rh-dttl.edgelab.dev
    secrets:
      - name: route53-creds
        stringData:
          secret-access-key: <put your actual key here>
      - name: eabsecret
        stringData:
          secret: <put your actual HMAC key here>

certificates:
  clusterIssuer: zerossl
  api:
    managed: true
    dnsNames:
      - api.hub.rh-dttl.edgelab.dev
  router:
    managed: true
    dnsNames:
      - apps.hub.rh-dttl.edgelab.dev
      - "*.apps.hub.rh-dttl.edgelab.dev"
  nlbRouter:
    managed: true
    dnsNames:
      - nlb-apps.hub.rh-dttl.edgelab.dev
      - "*.nlb-apps.hub.rh-dttl.edgelab.dev"
