{{- if .Values.certificates.router.managed -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-default
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  dnsNames:
    {{- toYaml .Values.certificates.router.dnsNames | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certificates.clusterIssuer }}
  secretName: router-cert
---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  defaultCertificate:
    name: router-cert
{{- end }}
{{- if .Values.certificates.nlbRouter.managed -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-nlb
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  dnsNames:
    {{- toYaml .Values.certificates.nlbRouter.dnsNames | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.certificates.clusterIssuer }}
  secretName: router-nlb-cert
{{- end }}
