---
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: cluster-applications
  namespace: {{ .Values.cluster.name }}
spec:
  workload:
    manifests:
    {{- range $path, $_ := .Files.Glob (printf "%s/*.yaml" $.Values.cluster.name) }}
      - {{ trim (tpl ($.Files.Get $path) $ | nindent 8) }}
    {{- end }}
