---
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: openshift-gitops
  namespace: {{ .Values.cluster.name }}
spec:
  workload:
    manifests:
    {{- range $path, $_ := .Files.Glob "gitops/*.yaml" }}
      - {{ trim (tpl ($.Files.Get $path) $ | nindent 8) }}
    {{- end }}
