{{- range .Values.disks }}
---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-storage-disk-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storageClassDevices:
    - storageClassName: localblock
      volumeMode: Block
      devicePaths:
        - {{ .path }}
{{ end }}
