global:
  resolve_timeout: 5m
  slack_api_url: "{{ .Values.slack.apiUrl }}"
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Watchdog
  - name: Default
    slack_configs:
      - channel: "{{ .Values.slack.channel }}"
        username: "{{ .Values.slack.username }}"
        icon_url: "{{ .Values.slack.iconUrl }}"
        send_resolved: true
        title: >-
          {{- .Values.slack.title | nindent 10 }}
        text: |-
          *Cluster:* {{ .Values.cluster.name }}
          {{- .Values.slack.text | nindent 10 }}
  - name: Critical
    slack_configs:
      - channel: "{{ .Values.slack.channel }}"
        username: "{{ .Values.slack.username }}"
        icon_url: "{{ .Values.slack.iconUrl }}"
        send_resolved: true
        title: >-
          {{- .Values.slack.title | nindent 10 }}
        text: |-
          {{ `{{` }} if eq .Status "firing" {{ `}}` }}:alert-siren: <!channel> :alert-siren:{{ `{{` }} end {{ `}}` }}
          *Cluster:* {{ .Values.cluster.name }}
          {{- .Values.slack.text | nindent 10 }}
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - alertname = InfoInhibitor
    - receiver: Critical
      match:
        severity: critical
