---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
spec:
  {{- with .Values.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - {{ .Values.mode }}
  resources:
    requests:
      storage: {{ .Values.size }}
