---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: windows-installer-{{ .Release.Name }}
spec:
  params:
    - name: winTenIsoDownloadURL
      {{- with .Values.winTenIsoDownloadURL }}
      default: {{ quote . }}
      {{- end }}
      type: string
    - name: autounattendConfigMapName
      default: windows-10-autounattend-{{ .Release.Name }}
      type: string
  tasks:
    - name: create-source-dv
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              name: windows-10-iso
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 7Gi
                volumeMode: Filesystem
              source:
                http:
                  url: $(params.winTenIsoDownloadURL)
        - name: waitForSuccess
          value: "true"
        - name: allowReplace:
          value: "true"
      taskRef:
        kind: Task
        name: modify-data-object
    - name: create-root-dv
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: windows-10-{{ .Release.Name }}-
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                volumeMode: Filesystem
              source:
                blank: {}
        - name: waitForSuccess
          value: "true"
      taskRef:
        kind: Task
        name: modify-data-object
    - name: create-vm-from-manifest
      params:
        - name: manifest
          value: |-
            apiVersion: kubevirt.io/v1alpha3
            kind: VirtualMachine
            metadata:
              generateName: windows-10-installer-{{ .Release.Name }}-
              annotation:
                description: Windows VM generated by windows-installer pipeline
              labels:
                app: windows-installer
                pipeline: windows-installer-{{ .Release.Name }}
            spec:
              runStrategy: RerunOnFailure
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: windows-installer
                spec:
                  domain:
                    cpu:
                     sockets: 2
                     cores: 1
                     threads: 1
                    resources:
                      requests:
                        memory: 4Gi
                    devices:
                      disks:
                        - name: installcdrom
                          cdrom:
                            bus: sata
                          bootOrder: 1
                        - name: rootdisk
                          bootOrder: 2
                          disk:
                            bus: virtio
                        - name: virtiocontainerdisk
                          cdrom:
                            bus: sata
                        - name: sysprepconfig
                          cdrom:
                            bus: sata
                      interfaces:
                        - bridge: {}
                          name: default
                      inputs:
                        - type: tablet
                          bus: usb
                          name: tablet
                  networks:
                    - name: default
                      pod: {}
                  volumes:
                    - name: installcdrom
                      dataVolume:
                        name: '$(tasks.create-source-dv.results.name)'
                    - name: rootdisk
                      dataVolume:
                        name: '$(tasks.create-root-dv.results.name)'
                    - name: virtiocontainerdisk
                      containerDisk:
                        image: kubevirt/virtio-container-disk
                    - name: sysprepconfig
                      sysprep:
                        configMap:
                          name: $(params.autounattendConfigMapName)
      runAfter:
        - create-source-dv
        - create-root-dv
      taskRef:
        kind: Task
        name: create-vm-from-manifest
    - name: wait-for-vmi-status
      params:
        - name: vmiName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: vmiNamespace
          value: ""
        - name: successCondition
          value: status.phase == Succeeded
        - name: failureCondition
          value: "status.phase in (Failed, Unknown)"
      runAfter:
        - create-vm-from-manifest
      taskRef:
        kind: Task
        name: wait-for-vmi-status
    - name: create-base-dv
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
              name: windows-10-{{ .Release.Name }}
              namespace: openshift-virtualization-os-images
            spec:
              storage: {}
              source:
                pvc:
                  name: $(tasks.create-root-dv.results.name)
                  namespace: {{ .Release.Namespace }}
        - name: waitForSuccess
          value: "true"
        - name: allowReplace
          value: "true"
      runAfter:
        - wait-for-vmi-status
      taskRef:
        kind: Task
        name:  modify-data-object
  finally:
    - name: cleanup-vm
      params:
        - name: vmName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: delete
          value: "true"
      taskRef:
        kind: Task
        name: cleanup-vm
      timeout: 10m0s
    - name: delete-vm-rootdisk
      params:
        - name: deleteObject
          value: "true"
        - name: deleteObjectKind
          value: DataVolume
        - name: deleteObjectName
          value: $(tasks.create-root-dv.results.name)
      taskRef:
        kind: Task
        name: modify-data-object
  results:
    - description: Name of the created base DataVolume
      name: baseDvName
      value: $(tasks.create-base-dv.results.name)
    - description: Namespace of the created base DataVolume
      name: baseDvNamespace
      value: $(tasks.create-base-dv.results.namespace)
