---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: windows-installer-{{ .Release.Name }}
spec:
  params:
    - name: winTenIsoDownloadURL
      {{- with .Values.winTenIsoDownloadURL }}
      default: {{ quote . }}
      {{- end }}
      type: string
    - name: autounattendConfigMapName
      default: windows-10-autounattend-{{ .Release.Name }}
      type: string
    - name: uniqueResourceName
      type: string
      default: windows-10-{{ .Release.Name }}
  tasks:
    - name: create-source-dv
      displayName: Import installer ISO
      description: Copies the installation ISO to the current project to prepare for an installation
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              name: windows-10-iso-{{ .Release.Name }}
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 7Gi
                volumeMode: Block
              source:
                pvc:
                  name: windows-10-iso
                  namespace: {{ .Release.Namespace }}
        - name: waitForSuccess
          value: "true"
        - name: allowReplace
          value: "true"
      taskRef:
        kind: Task
        name: modify-data-object
    - name: create-root-dv
      displayName: Create installation destination
      description: Creates a disk image for installing Windows into
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: windows-10-{{ .Release.Name }}-
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                volumeMode: Block
              source:
                blank: {}
        - name: waitForSuccess
          value: "true"
        - name: allowReplace
          value: "true"
      taskRef:
        kind: Task
        name: modify-data-object
    - name: create-vm-from-manifest
      displayName: Create Windows VM
      description: Creates a Windows VM to perform the installation and customization
      params:
        - name: manifest
          value: |-
            apiVersion: kubevirt.io/v1alpha3
            kind: VirtualMachine
            metadata:
              generateName: windows-10-installer-{{ .Release.Name }}-
              annotation:
                description: Windows VM generated by windows-installer pipeline
              labels:
                app: windows-installer
                pipeline: windows-installer-{{ .Release.Name }}
            spec:
              runStrategy: RerunOnFailure
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: windows-installer
                spec:
                  domain:
                    cpu:
                     sockets: 2
                     cores: 1
                     threads: 1
                    resources:
                      requests:
                        memory: 4Gi
                    devices:
                      disks:
                        - name: installcdrom
                          cdrom:
                            bus: sata
                          bootOrder: 1
                        - name: rootdisk
                          bootOrder: 2
                          disk:
                            bus: virtio
                        - name: virtiocontainerdisk
                          cdrom:
                            bus: sata
                        - name: sysprepconfig
                          cdrom:
                            bus: sata
                      interfaces:
                        - masquerade: {}
                          name: default
                          model: e1000e
                      inputs:
                        - type: tablet
                          bus: usb
                          name: tablet
                  networks:
                    - name: default
                      pod: {}
                  volumes:
                    - name: installcdrom
                      dataVolume:
                        name: '$(tasks.create-source-dv.results.name)'
                    - name: rootdisk
                      dataVolume:
                        name: '$(tasks.create-root-dv.results.name)'
                    - name: virtiocontainerdisk
                      containerDisk:
                        image: quay.io/kubevirt/virtio-container-disk:{{ .Values.virtioContainerDiskVersion }}
                    - name: sysprepconfig
                      sysprep:
                        configMap:
                          name: $(params.autounattendConfigMapName)
      runAfter:
        - create-source-dv
        - create-root-dv
      taskRef:
        kind: Task
        name: create-vm-from-manifest
    - name: wait-for-vmi-status
      displayName: Wait for VM Shutdown
      description: Wait for the installation and customization process to finish, after which the VM will shut down
      params:
        - name: vmiName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: vmiNamespace
          value: ""
        - name: successCondition
          value: status.phase == Succeeded
        - name: failureCondition
          value: "status.phase in (Failed, Unknown)"
      runAfter:
        - create-vm-from-manifest
      taskRef:
        kind: Task
        name: wait-for-vmi-status
    - name: create-base-dv
      displayName: Snapshot VM disk image
      description: Saves the VM disk image as a new gold image to allow easy VM creation from it
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              annotations:
                "cdi.kubevirt.io/storage.bind.immediate.requested": "true"
              name: $(params.uniqueResourceName)
              namespace: openshift-virtualization-os-images
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
                volumeMode: Block
              source:
                pvc:
                  name: $(tasks.create-root-dv.results.name)
                  namespace: {{ .Release.Namespace }}
        - name: waitForSuccess
          value: "true"
        - name: allowReplace
          value: "true"
      runAfter:
        - wait-for-vmi-status
      taskRef:
        kind: Task
        name:  modify-data-object
    - name: create-data-source
      displayName: Configure template
      description: Wires the application to use the new disk image snapshot, instead of the previously customized image
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataSource
            metadata:
              name: windows-10-{{ .Release.Name }}
              namespace: openshift-virtualization-os-images
            spec:
              source:
                pvc:
                  name: $(params.uniqueResourceName)
                  namespace: openshift-virtualization-os-images
        - name: waitForSuccess
          value: "true"
        - name: allowReplace
          value: "true"
      runAfter:
        - create-base-dv
      taskRef:
        kind: Task
        name:  modify-data-object
  finally:
    - name: cleanup-vm
      displayName: Remove VM
      description: Tears down the ephemeral VM instance used for installation and customization
      params:
        - name: vmName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: delete
          value: "true"
      taskRef:
        kind: Task
        name: cleanup-vm
      timeout: 10m0s
    - name: delete-iso
      displayName: Remove ISO
      description: Tears down the temporarily copied ISO file from installation
      params:
        - name: deleteObject
          value: "true"
        - name: deleteObjectKind
          value: DataVolume
        - name: deleteObjectName
          value: $(tasks.create-source-dv.results.name)
      taskRef:
        kind: Task
        name: modify-data-object
    - name: delete-vm-rootdisk
      displayName: Remove VM disk image
      description: Tears down the disk image from the installation
      params:
        - name: deleteObject
          value: "true"
        - name: deleteObjectKind
          value: DataVolume
        - name: deleteObjectName
          value: $(tasks.create-root-dv.results.name)
      taskRef:
        kind: Task
        name: modify-data-object
  results:
    - description: Name of the created base DataVolume
      name: baseDvName
      value: $(tasks.create-base-dv.results.name)
    - description: Namespace of the created base DataVolume
      name: baseDvNamespace
      value: $(tasks.create-base-dv.results.namespace)
