---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  labels:
  name: windows-10-{{ .Release.Name }}{{ with .Values.global.gitCommit }}-{{ substr 0 7 . }}{{ end }}
  namespace: openshift-virtualization-os-images
spec:
  source:
    pvc:
      name: windows-10-{{ .Release.Name }}{{ with .Values.global.gitCommit }}-{{ substr 0 7 . }}{{ end }}
      namespace: openshift-virtualization-os-images
