apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: windows-installer-{{ .Release.Name }}{{ with .Values.global.gitCommit }}-{{ substr 0 7 . }}{{ end }}
  labels:
    tekton.dev/pipeline: windows-installer-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  pipelineRef:
    name: windows-installer-{{ .Release.Name }}
  timeouts:
    pipeline: {{ .Values.buildTimeout }}
  {{- with .Values.global.gitCommit }}
  params:
    - name: uniqueResourceName
      value: windows-10-{{ $.Release.Name }}-{{ substr 0 7 . }}
  {{- end }}
