---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    defaults.template.kubevirt.io/disk: rootdisk
    defaults.template.kubevirt.io/network: default
    description: Template for the {{ .Release.Name | replace "-" " " | title }}
    iconClass: icon-windows
    name.os.template.kubevirt.io/win10: {{ .Release.Name | replace "-" " " | title }}
    openshift.io/display-name: {{ .Release.Name | replace "-" " " | title }}
    openshift.io/provider-display-name: Red Hat and Deloitte
    openshift.kubevirt.io/pronounceable-suffix-for-name-expression: "true"
    tags: kubevirt,virtualmachine,windows
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.kubevirt.io/provider: Red Hat and Deloitte
    template.kubevirt.io/provider-support-level: Full
    template.kubevirt.io/provider-url: https://www.redhat.com
    template.kubevirt.io/version: v1alpha1
    template.openshift.io/bindable: "false"
  labels:
    flavor.template.kubevirt.io/medium: "true"
    os.template.kubevirt.io/win10: "true"
    template.kubevirt.io/type: vm
    template.kubevirt.io/version: v0.26.0
    workload.template.kubevirt.io/desktop: "true"
  name: {{ .Release.Name }}
  namespace: openshift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}-rdp
  spec:
    selector:
      kubevirt.io/domain: ${NAME}
    ports:
      - name: rdp
        protocol: TCP
        port: 3389
        targetPort: 3389
        nodePort: ${{ "{{" }}NODE_PORT{{ "}}" }}
    externalTrafficPolicy: ${EXTERNAL_TRAFFIC}
    type: NodePort
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.memory.guest",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 4294967296
          }, {
            "name": "windows-virtio-bus",
            "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
            "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
            "rule": "enum",
            "message": "virtio disk bus type has better performance, install virtio drivers in VM and change bus type",
            "values": ["virtio"],
            "justWarning": true
          }, {
            "name": "windows-disk-bus",
            "path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
            "valid": "jsonpath::.spec.domain.devices.disks[*].disk.bus",
            "rule": "enum",
            "message": "disk bus has to be either virtio or sata or scsi",
            "values": ["virtio", "sata", "scsi"]
          }, {
            "name": "windows-cd-bus",
            "path": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
            "valid": "jsonpath::.spec.domain.devices.disks[*].cdrom.bus",
            "rule": "enum",
            "message": "cd bus has to be sata",
            "values": ["sata"]
          }
        ]
    labels:
      app: ${NAME}
      vm.kubevirt.io/template: {{ .Release.Name }}
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.26.0
    name: ${NAME}
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ${NAME}
      spec:
        sourceRef:
          kind: DataSource
          name: ${DATA_SOURCE_NAME}
          namespace: ${DATA_SOURCE_NAMESPACE}
        storage:
          resources:
            requests:
              storage: {{ .Values.template.diskSize }}
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: medium
          vm.kubevirt.io/os: windows10
          vm.kubevirt.io/workload: desktop
        labels:
          kubevirt.io/domain: ${NAME}
          kubevirt.io/size: medium
      spec:
        domain:
          clock:
            timer:
              hpet:
                present: false
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
          cpu:
            cores: 1
            sockets: {{ .Values.template.cpuCores }}
            threads: 1
          devices:
            disks:
            - disk:
                bus: sata
              name: rootdisk
            inputs:
            - bus: usb
              name: tablet
              type: tablet
            interfaces:
            - model: e1000e
              name: default
              masquerade: {}
              ports:
              - name: rdp
                protocol: TCP
                port: 3389
          features:
            hyperv:
              spinlocks:
                spinlocks: 8191
          machine:
            type: pc-q35-rhel9.2.0
          memory:
            guest: {{ .Values.template.memory }}
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 3600
        volumes:
        - dataVolume:
            name: ${NAME}
          name: rootdisk
parameters:
- description: VM name
  from: windows-[a-z0-9]{6}
  generate: expression
  name: NAME
- description: Name of the DataSource to clone
  name: DATA_SOURCE_NAME
  value: windows-10-{{ .Release.Name }}
- description: Namespace of the DataSource
  name: DATA_SOURCE_NAMESPACE
  value: openshift-virtualization-os-images
- description: The port on all nodes to bind for RDP for this VM
  name: NODE_PORT
  value: "31389"
- description: External traffic policy for the Service
  name: EXTERNAL_TRAFFIC
  value: Cluster
