---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  annotations:
    iconClass: icon-windows
    openshift.io/display-name: {{ .Release.Name | replace "-" " " | title }}
    openshift.io/documentation-url: https://access.redhat.com
    openshift.io/provider-display-name: Red Hat and Deloitte
    openshift.io/support-url: https://access.redhat.com
    tags: kubevirt,windows
  labels:
    instancetype.kubevirt.io/os-type: windows
    instancetype.kubevirt.io/vendor: redhat.com
  name: windows.10.{{ .Release.Name }}
spec:
  clock:
    preferredTimer:
      hpet:
        present: false
      pit:
        tickPolicy: delay
      rtc:
        tickPolicy: catchup
  cpu:
    preferredCPUTopology: preferSockets
  devices:
    preferredAutoattachInputDevice: true
    preferredDiskBus: virtio
    preferredInputBus: virtio
    preferredInputType: tablet
    preferredInterfaceModel: e1000e
  features:
    preferredHyperv:
      spinlocks:
        spinlocks: 8191
  preferredTerminationGracePeriodSeconds: 3600
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
