---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bucket-secrets-job-namespace-edit
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: bucket-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bucket-secrets-job-operator-config-{{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-image-registry-operator
subjects:
  - kind: ServiceAccount
    name: bucket-secrets
    namespace: {{ .Release.Namespace }}
{{- if .Values.useServiceCA }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bucket-secrets-update-configmap
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: bucket-secrets
    namespace: {{ .Release.Namespace }}
{{- end }}
